server:
  port: 8081
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    #  # Payment Service MongoDB Configuration
    data:
      mongodb:
        host: ${MONGODB_HOST}
        port: ${MONGODB_PORT}
        database: ${MONGODB_DATABASE}
        username: ${MONGODB_USERNAME}
        password: ${MONGODB_PASSWORD}
        authentication-mechanism: ${MONGODB_AUTH_MECHANISM}




# Prometheus Configuration
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
