global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'customer-service'
    static_configs:
      - targets: ['customer-service:8081']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8084']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8083']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8086']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8082']
