spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    #  # Payment Service MongoDB Configuration
    data:
      mongodb:
        host: ${MONGODB_HOST}
        port: ${MONGODB_PORT}
        database: ${MONGODB_DATABASE}
        username: ${MONGODB_USERNAME}
        password: ${MONGODB_PASSWORD}
        #        authentication-database: ${MONGODB_AUTH_DATABASE}
        authentication-mechanism: ${MONGODB_AUTH_MECHANISM}
#        ssl: ${MONGODB_SSL_ENABLED:false} # Default to false if not provided


  # Flyway Migration Configuration

  flyway:
    locations: classpath:db/migration

# Prometheus Configuration
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 8081