server:
  port: 8086
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# kafka
kafka:
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.type.mapping: paymentConfirmation:code.with.vanilson.paymentservice.notification.PaymentNotificationRequest

application:
  config:
    product-url: http://localhost:8082/api/v1/products

# Flyway Migration Configuration
# Flyway Migration Configuration
flyway:
  locations: classpath:db/migration/
  baseline-on-migrate: true
  enabled: true
  baseline-description: "init"
  baseline-version: 0  # Different baseline version to avoid conflict
  repair: true
  outOfOrder: true
  ignoreMigrationPatterns: "*:ignored"  # Use ':' instead of '=' for key-value pairs
