name: Ecommerce CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy ecommerce microservices
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AdoptOpenJDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build all services with Maven
        run: |
          mvn clean package --file pom.xml

      - name: Build and push config-service Docker image
        run: |
          cd backend/config-service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/config-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/config-service:latest

      - name: Build and push discovery-service Docker image
        run: |
          cd ../discovery-service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/discovery-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/discovery-service:latest

      - name: Build and push customer-service Docker image
        run: |
          cd ../customer-service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/customer-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/customer-service:latest

      - name: Build and push product-service Docker image
        run: |
          cd ../product-service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/product-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/product-service:latest

      - name: Build and push order-service Docker image
        run: |
          cd ../order-service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/order-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/order-service:latest

  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Check out the actual pull request commit
          fetch-depth: 0  # Full history required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
